def get_error():
    pass    